### ISSUE TITLE
[PE-D][Tester C] Address allows for empty strings

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T12-2/tp#106]
Not sure if this is intended, but you can edit_person a/ with  an empty string whereas this does not occur for any other field. Could potentially be confusing for user.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: seraphimstreets/ped#5

**Comment by Kurtyjlee** [comment]
## TODO:
- This behaviour should be consistent with the documentation and other commands. 
- Fix this behaviour

**Comment by Kurtyjlee** [comment]
Updated by @nicleongyj
