### ISSUE TITLE
[PE-D][Tester C] Not able to create groups with whitespace

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T12-2/tp#111]
It seems that the app currently only accepts one word groups. This may make it somewhat less useful for some users. 

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: seraphimstreets/ped#6

**Comment by Kurtyjlee** [comment]
## TODO:
- Fix bug / update docs to let users know of the limitations

**Comment by Kurtyjlee** [comment]
Bug fixed by @nicleongyj
