### ISSUE TITLE
Configure add command to take in optional parameters

### ISSUE THREAD

**Issue by leezhengjing** [AY2324S1-CS2103T-T12-2/tp#34]
- Add command should permit minimally just the name parameter. Every other parameter is optional
- Currently:
- Example: add n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25
- Expected functionality:
- Example: add n/John Doe

**Comment by Kurtyjlee** [comment]
Issue done in PR #35
