### ISSUE TITLE
[PE-D][Tester A] Invalid birthday for a newly added person

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T12-2/tp#86]
![image.png](https://raw.githubusercontent.com/StevenLiudw/ped/main/files/3ea9c539-c21d-457c-a2ad-5075c0489fd1.png)

Should avoid to add a new person if their birthday is invalid dates.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: StevenLiudw/ped#1

**Comment by Kurtyjlee** [comment]
Already flagged
