### ISSUE TITLE
[PE-D][Tester E] Person with invalid birthday can be added

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T12-2/tp#88]
Person with a birthday which is far into the future can be added using the add_person command. Some checks to check that the birthday has not passed at the current point in time could be helpful to improve this! 

![Screenshot 2023-11-03 at 4.13.51 PM.png](https://raw.githubusercontent.com/zhengyup/ped/main/files/14f841bd-1a01-475e-9b07-cdb91de3408d.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: zhengyup/ped#1

**Comment by Kurtyjlee** [comment]
## TODO:
- Add a fix for this

**Comment by Kurtyjlee** [comment]
Bug fix by @Ken-Lai
